import { useMemo, useState } from "react";
import { useLocation } from "wouter";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { BookOpen, Check, Compass, FileHeart, Goal, HeartPulse, Home, Leaf, LockKeyhole, LogOut, Menu, Music2, Save, Settings, ShieldCheck, Sparkles, Target, TrendingUp, Users, X } from "lucide-react";
import { clearGuestDemoData, readGuestBoolean, readGuestJournal, writeGuestBoolean, writeGuestJournal, type GuestJournalEntry } from "@/lib/guestDemoStorage";
import Guides from "@/pages/Guides";
import Community from "@/pages/Community";

const navItems = [
  { path: "/dashboard", label: "Overview", icon: Home },
  { path: "/check-ins", label: "Today", icon: HeartPulse },
  { path: "/progress", label: "Progress", icon: TrendingUp },
  { path: "/journal", label: "Journal", icon: BookOpen },
  { path: "/goals", label: "Goals", icon: Goal },
  { path: "/rules", label: "Boundaries", icon: ShieldCheck },
  { path: "/guides", label: "Guides", icon: Compass },
  { path: "/community", label: "Community", icon: Users },
  { path: "/music", label: "Music reset", icon: Music2 },
  { path: "/devotional", label: "Devotional", icon: Sparkles },
  { path: "/newsletter", label: "Newsletter", icon: FileHeart },
];

const dimensions = ["Body", "Mind", "Emotions", "Relationships", "Work", "Money", "Purpose", "Home", "Rest"];
const guideCards = [
  { title: "A ten-minute reset", type: "Activity", body: "Put both feet on the floor, take five slow breaths, and name the next kind action." },
  { title: "When the urge arrives", type: "In the moment", body: "Delay the decision by ten minutes. Change rooms, drink water, and contact a safe person." },
  { title: "Repair without performance", type: "Relationships", body: "Say what happened, name your part, and ask what would help rebuild trust." },
];


function DemoContent({ path, notify }: { path: string; notify: (message: string) => void }) {
  const [, setLocation] = useLocation();
  const [journalBody, setJournalBody] = useState("");
  const [entries, setEntries] = useState<GuestJournalEntry[]>(readGuestJournal);
  const [checkedIn, setCheckedIn] = useState(() => readGuestBoolean("checkIn"));
  const [goalStep, setGoalStep] = useState(() => readGuestBoolean("goalStep"));
  const [ruleKept, setRuleKept] = useState(() => readGuestBoolean("rule"));

  const saveJournal = () => { const body = journalBody.trim(); if (!body) return; const next = [{ id: Date.now(), body, createdAt: new Date().toISOString() }, ...entries]; setEntries(next); writeGuestJournal(next); setJournalBody(""); notify("Saved privately in this browser."); };
  const title = navItems.find((item) => item.path === path)?.label ?? "ReForge demo";

  if (path === "/journal") return <Page title="Private reflection" description="This demo journal stays in this browser only."><Card className="nature-card"><CardHeader><CardTitle className="font-serif text-2xl">Make room for the truth.</CardTitle><CardDescription>Nothing here is uploaded or shared in guest mode.</CardDescription></CardHeader><CardContent className="space-y-4"><Textarea value={journalBody} onChange={(event) => setJournalBody(event.target.value)} placeholder="What feels important today?" className="min-h-40 rounded-2xl" /><Button onClick={saveJournal} disabled={!journalBody.trim()} className="rounded-full gap-2"><Save className="h-4 w-4" /> Save locally</Button></CardContent></Card><div className="space-y-3">{entries.length === 0 ? <Empty title="Your pages are waiting." body="Use the private composer above to add a first reflection." /> : entries.map((entry) => <Card key={entry.id} className="nature-card"><CardContent className="p-5"><p className="text-xs text-muted-foreground">{new Date(entry.createdAt).toLocaleString()}</p><p className="mt-3 whitespace-pre-wrap text-sm leading-7">{entry.body}</p></CardContent></Card>)}</div></Page>;
  if (path === "/check-ins") return <Page title="Today" description="A small check-in can change the shape of a day."><Card className="nature-card"><CardHeader><CardTitle className="font-serif text-2xl">Morning check-in</CardTitle><CardDescription>How supported do you feel right now?</CardDescription></CardHeader><CardContent className="space-y-5"><input aria-label="Demo check-in score" type="range" min="1" max="5" defaultValue="3" className="w-full accent-[var(--primary)]" /><Button onClick={() => { setCheckedIn(true); writeGuestBoolean("checkIn", true); notify("Check-in saved locally."); }} className="rounded-full">{checkedIn ? "Checked in today" : "Save check-in"}</Button></CardContent></Card><Empty title="Evening check-in" body="Return later to notice what helped, what was hard, and what you want to carry forward." /></Page>;
  if (path === "/progress") return <Page title="Progress across your life" description="Progress is a practice, not a verdict."><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{dimensions.map((dimension, index) => <Card key={dimension} className="nature-card"><CardContent className="p-5"><div className="flex items-center justify-between"><p className="font-serif text-xl">{dimension}</p><span className="font-semibold text-primary">{62 + (index % 4) * 7}%</span></div><div className="mt-4 h-2 rounded-full bg-muted"><div className="h-2 rounded-full bg-primary" style={{ width: `${62 + (index % 4) * 7}%` }} /></div><p className="mt-3 text-xs text-muted-foreground">A demo signal for this browser.</p></CardContent></Card>)}</div></Page>;
  if (path === "/goals") return <Page title="Goals that can hold you" description="Choose one horizon and make the next step visible."><Card className="nature-card"><CardHeader><Badge className="w-fit rounded-full bg-primary/10 text-primary hover:bg-primary/10">30-day horizon</Badge><CardTitle className="font-serif text-3xl">Return to a steadier morning</CardTitle><CardDescription>One gentle structure that supports the rest of the day.</CardDescription></CardHeader><CardContent><button type="button" onClick={() => { setGoalStep(!goalStep); writeGuestBoolean("goalStep", !goalStep); }} className="flex w-full items-center gap-3 rounded-xl border p-4 text-left hover:border-primary/40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><span className={`grid h-7 w-7 place-items-center rounded-full ${goalStep ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground"}`}>{goalStep ? <Check className="h-4 w-4" /> : "1"}</span><span><strong className="block">Prepare tomorrow tonight</strong><span className="text-sm text-muted-foreground">Tap to mark this demo step complete.</span></span></button></CardContent></Card></Page>;
  if (path === "/rules") return <Page title="Boundaries that protect the life you want" description="Practice one clear rule at a time, without shame or perfectionism."><Card className="nature-card"><CardHeader><Badge variant="outline" className="w-fit rounded-full">Daily review</Badge><CardTitle className="font-serif text-3xl">I do not make big decisions while overwhelmed.</CardTitle><CardDescription>Pause, regulate, and return to the decision with support.</CardDescription></CardHeader><CardContent><Button onClick={() => { setRuleKept(!ruleKept); writeGuestBoolean("rule", !ruleKept); notify(!ruleKept ? "Boundary marked as kept." : "Boundary review reopened."); }} className="rounded-full">{ruleKept ? "Reviewed today" : "Mark reviewed"}</Button></CardContent></Card></Page>;
  if (path === "/guides") return <Guides />;
  if (path === "/community") return <Community />;
  if (path === "/settings") return <Page title="Settings and privacy" description="Guest mode keeps this demo local to your browser."><Card className="nature-card"><CardContent className="space-y-4 p-6"><div className="flex items-start gap-3"><LockKeyhole className="mt-1 h-5 w-5 text-primary" /><p className="text-sm leading-7">No account, cookie session, or cloud profile is required in this demo. Clear this browser's site data to remove local demo entries.</p></div><Button variant="outline" onClick={() => { clearGuestDemoData(); window.location.reload(); }} className="rounded-full">Reset local demo</Button></CardContent></Card></Page>;
  return <Page title="A quiet place to begin again" description="Explore ReForge without an account. Your demo actions stay in this browser."><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Today" value={checkedIn ? "Saved" : "Open"} /><Metric label="Journal" value={`${entries.length} pages`} /><Metric label="Goal" value={goalStep ? "Moving" : "Ready"} /><Metric label="Boundary" value={ruleKept ? "Kept" : "Review"} /></div><Card className="nature-card"><CardContent className="flex flex-col gap-4 p-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-serif text-2xl">Keep the next step small.</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Start with a check-in, write one honest line, or browse a practical guide.</p></div><Button onClick={() => setLocation("/check-ins")} className="rounded-full">Open today</Button></CardContent></Card></Page>;
}

function Page({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <div className="space-y-6"><header><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">Guest demo</p><h1 className="mt-2 font-serif text-4xl leading-tight sm:text-5xl">{title}</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-muted-foreground">{description}</p></header>{children}</div>; }
function Empty({ title, body }: { title: string; body: string }) { return <Card className="nature-card border-dashed"><CardContent className="p-7 text-center"><Leaf className="mx-auto h-6 w-6 text-primary" /><p className="mt-3 font-serif text-xl">{title}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{body}</p></CardContent></Card>; }
function Metric({ label, value }: { label: string; value: string }) { return <Card className="nature-card"><CardContent className="p-5"><p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">{label}</p><p className="mt-3 font-serif text-2xl text-primary">{value}</p></CardContent></Card>; }

export default function GuestDemoWorkspace({ children: _children }: { children: React.ReactNode }) {
  const [location, setLocation] = useLocation();
  const [mobileOpen, setMobileOpen] = useState(false);
  const [toast, setToast] = useState("");
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 2400); };
  const path = useMemo(() => location.split("?")[0], [location]);
  return <div className="min-h-screen bg-background text-foreground"><div className="border-b border-primary/15 bg-primary/8 px-4 py-2 text-center text-xs text-primary">Public demo mode · no sign-in required · data stays in this browser</div><div className="flex min-h-[calc(100vh-2rem)]"><aside className={`${mobileOpen ? "fixed inset-y-0 left-0 z-50 flex" : "hidden"} w-72 shrink-0 flex-col border-r border-border/70 bg-sidebar p-4 lg:flex`}><div className="flex items-center justify-between border-b border-sidebar-border/60 pb-5"><button type="button" onClick={() => setLocation("/dashboard")} className="text-left"><span className="font-serif text-2xl font-semibold text-sidebar-foreground">Re<span className="text-primary">Forge</span></span><span className="block text-[10px] uppercase tracking-[0.18em] text-sidebar-foreground/55">Guest demo</span></button><button type="button" onClick={() => setMobileOpen(false)} className="rounded-lg p-2 text-sidebar-foreground/60 hover:bg-sidebar-accent lg:hidden" aria-label="Close navigation"><X className="h-4 w-4" /></button></div><nav className="mt-5 flex-1 space-y-1" aria-label="Demo navigation">{navItems.map((item) => <button key={item.path} type="button" onClick={() => { setLocation(item.path); setMobileOpen(false); }} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm transition-colors ${path === item.path ? "bg-primary/12 font-medium text-primary" : "text-sidebar-foreground/70 hover:bg-sidebar-accent hover:text-sidebar-foreground"}`}><item.icon className="h-4 w-4" aria-hidden="true" />{item.label}</button>)}</nav><button type="button" onClick={() => setLocation("/")} className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-sidebar-foreground/65 hover:bg-sidebar-accent"><LogOut className="h-4 w-4" />Exit demo</button></aside>{mobileOpen && <button type="button" aria-label="Close navigation overlay" onClick={() => setMobileOpen(false)} className="fixed inset-0 z-40 bg-black/20 lg:hidden" />}<div className="min-w-0 flex-1"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-border/60 bg-background/90 px-4 backdrop-blur sm:px-6"><div className="flex items-center gap-3"><button type="button" onClick={() => setMobileOpen(true)} className="rounded-xl p-2 text-foreground/70 hover:bg-muted lg:hidden" aria-label="Open navigation"><Menu className="h-5 w-5" /></button><span className="font-serif text-xl font-semibold">{navItems.find((item) => item.path === path)?.label ?? "ReForge"}</span></div><Badge variant="outline" className="rounded-full gap-1.5"><Sparkles className="h-3 w-3" /> Demo only</Badge></header><main className="mx-auto max-w-6xl p-4 sm:p-6 lg:p-8"><DemoContent path={path} notify={notify} /></main></div></div>{toast && <div role="status" className="fixed bottom-5 right-5 z-[60] rounded-full bg-foreground px-4 py-2 text-sm text-background shadow-lg">{toast}</div>}</div>;
}
